services:
  - type: worker
    name: ai-dart-coach
    env: python
    region: frankfurt  # или singapore, ohio, oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Вы установите это вручную
      - key: ADMIN_IDS
        value: "8443012380"
      - key: TEST_MODE
        value: "True"
    plan: free
    autoDeploy: true
